-- Tabla Kits
CREATE TABLE IF NOT EXISTS Kits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    imagen VARCHAR(300) NOT NULL DEFAULT '',
    descripcion TEXT NOT NULL,
    precio DECIMAL(10,2) NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT 1,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla KitBeneficios
CREATE TABLE IF NOT EXISTS KitBeneficios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    kit_id INT NOT NULL,
    beneficio VARCHAR(255) NOT NULL,
    FOREIGN KEY (kit_id) REFERENCES Kits(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

